services:
  app:
    container_name: hyperf-example-app
    tty: true
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/var/www
    ports:
      - 9501:9501
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    container_name: hyperf-example-mysql
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  phpmyadmin:
    container_name: hyperf-example-phpmyadmin
    build:
      context: .docker
      dockerfile: phpmyadmin.Dockerfile
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=0
      - MEMORY_LIMIT=1024M
      - UPLOAD_LIMIT=1024M
      - MAX_EXECUTION_TIME=0
      - UPLOAD_LIMI= 6096K
    depends_on:
      - mysql