name: CI - Hyperf

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------
      # Checkout do código
      # ----------------------------
      - name: Checkout do código
        uses: actions/checkout@v4

      # ----------------------------
      # Configurar Docker Buildx com suporte a cache
      # ----------------------------
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # ----------------------------
      # Build da imagem com cache integrado do GitHub Actions
      # ----------------------------
      - name: Build da imagem de desenvolvimento (com cache GHA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: myapp:test
          load: true # carrega a imagem localmente no runner
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ----------------------------
      # Instalar dependências Composer
      # ----------------------------
      - name: Instalar dependências Composer
        run: |
          docker run --rm \
            -v $PWD:/var/www \
            -w /var/www \
            myapp:test composer install --prefer-dist --no-interaction --no-progress

      # ----------------------------
      # Rodar Linter (Pint, PHPStan, etc)
      # ----------------------------
      - name: Rodar Linter
        run: |
          docker run --rm \
            -v $PWD:/var/www \
            -w /var/www \
            myapp:test composer lint || true
      # ----------------------------
      # Listar arquivos
      # ----------------------------
      - name: Listar arquivos
        run: |
          docker run --rm \
            -v $PWD:/var/www \
            -w /var/www \
            myapp:test ls -lah

      # - name: Pest
      #   run: |
      #     docker run --rm \
      #       -v $PWD:/var/www \
      #       -w /var/www \
      #       myapp:test composer test tests/Unit/AccountUnitTest.php

      - name: Pest
        run: |
          docker run --rm \
            -v $PWD:/var/www \
            -w /var/www \
            myapp:test php vendor/bin/pest tests/Unit/EmailUnitTest.php

      # ----------------------------
      # Rodar Testes (Pest/PHPUnit)
      # ----------------------------
      # - name: Rodar Testes
      #   run: |
      #     docker run --rm \
      #       -v $PWD:/var/www \
      #       -w /var/www \
      #       myapp:test composer test -- tests/Unit/AccountUnitTest.php
